### ISSUE TITLE
No se puede crear opciones de una votación

### ISSUE THREAD

**Issue by Josdelsan** [decide-part-aracena/decide-part-aracena#108]
**Descripción:** Se observa que al intentar crear opciones desde el frontend de administración de preguntas de una votación no se pueden crear opciones. Solamente aparece la opción de seleccionar tipo Si/No, nombre y descripción.

**Contexto:** Para probar este error se debe descargar el commit c2005a49221fbd830f3c7c83b145cd2cb1208387 y ejecutar el servidor de django o lanzar la aplicación con docker.

**Pruebas:** Se ha comprobado que se pueden añadir opciones sin problema desde el panel de administrador de django.

**Comment by aisqazcev** [comment]
Se ha podido resolver, y ahora se pueden crear varias opciones. Se puede probar en el commit 3dcc5e729fd7db1a5cac450d64c9b0e5606b219b, aún queda cambiar el showUpdate de esto.
