### ISSUE TITLE
Votaciones creadas desde la interfaz no se muestran correctamente

### ISSUE THREAD

**Issue by rosmolarr** [decide-part-aracena/decide-part-aracena#109]
Cuando creas una votación desde la interfaz de admin de decide, se añade a la pagina principal como "votación terminada".Si pones la votación en empezada, sigue apareciendoe en terminada, y asi para todos los estados. Sin embargo, si la votación la creas desde la pagina de admin de django, se añade bien. Por lo que tiene que ser algun problema con la forma en la que se crea la votación, ¿puede ser que se cree diferente y no se muestre porque cambie algo?

**Comment by rosmolarr** [comment]
Estoy mirando y la diferencia que encuentro entre las dos votaciones (una creada desde admin y otra desde la interfaz) es que en la de admin el tally se inicializa vacio y en la de la interfaz no. Puede ser que por ahi este el problema.

**Comment by lausalbra** [comment]
Lo he comprobado desde mi rama y con el ultimo commit de develop y no observo problemas sobre el tema, de todos modos estare pendiente.

**Comment by Josdelsan** [comment]
Debido a que nadie ha encontrado el problema de nuevo, se cierra la incidencia por inactividad. En caso de que alguien volviera a encontrar el problema puede reabrir esta incidencia o mencionarla.
