### ISSUE TITLE
Modificación de las vistas de Voting para adecuarlo a nuevo recuento

### ISSUE THREAD

**Issue by alecarnun** [decide-part-aracena/decide-part-aracena#113]
El modelo voting tiene dos nuevos atributos (Nuevo Recuento #102 ), lo cual implica una actualizacion de los forms de voting que puede ver el usuario

**Comment by lausalbra** [comment]
Se procede a actualizar la vista de voting e incluir el nuevo metodo de recuento. Se puede ver en el commit de mi propia rama  b9d02f89656fc85eb5d606012dc57c94b9abab83
