### ISSUE TITLE
Modificacion de la visualizacion de los resultados para nuevo tipo de recuento (D'hont)

### ISSUE THREAD

**Issue by alecarnun** [decide-part-aracena/decide-part-aracena#114]
Al haber un nuevo tipo de metodo de recuento habra que adaptar la visualizacion de los resultados para adecuarse a los nuevos atributos #102 
El metodo de recuento D'hont usa escaños (atributo seats) para calcular al ganador

**Comment by lNoelia** [comment]
No se va a implementar debido a la falta de tiempo
