### ISSUE TITLE
No es posible visualizar las opciones de questions 

### ISSUE THREAD

**Issue by aisqazcev** [decide-part-aracena/decide-part-aracena#118]
Descripción: Actualmente no es posible ver el contenido de cada question desde la vista de la lista de questions. 

Contexto: Descargar commit 7cff313fa879b09f2188fc1b95101b9f699aede7 para probar este error y ejecutar en servidor django. 

Pruebas: Se ha comprobado que se pueden visualizar y editar opciones sin problema desde el panel de administrador de django.

**Comment by mansanrod4** [comment]
Issue completada.
