### ISSUE TITLE
Botón sí/no de question no tiene en cuenta formulario de question 

### ISSUE THREAD

**Issue by aisqazcev** [decide-part-aracena/decide-part-aracena#120]
Descripción: Se observa que al pulsar botón tipo Sí/No de question sigue siendo necesario añadir datos en los formularios inferiores de question. Por tanto, el usuario se ve obligado a escribir en ellos y se genera 4 opciones finalmente. 

Contexto: Para probar este error y solucionarlo habrá que descargar commit 7cff313fa879b09f2188fc1b95101b9f699aede7, realizar migrate y ejecutar en servidor django. Será necesario añadir el  parametro  'optionSiNo' en la clase QuestionForm de forms.py.

Pruebas: Se ha comprobado que esto no ocurre  desde el panel de administrador de django.

**Comment by olisanrod** [comment]
Solución: finalmente la solución ha consistido en crear un nuevo formulario que contemple solo la descripción de la pregunta y tenga marcado por defecto la casilla "opción Si/No" de esta forma, el resto de campos serán rellenados de forma automática. A su vez ahora hay dos botones de creación: uno para votaciones con múltiples respuestas, y otro para votaciones solo de este tipo (Si/No).
