### ISSUE TITLE
Error en la vista de administrador principal

### ISSUE THREAD

**Issue by lausalbra** [decide-part-aracena/decide-part-aracena#143]
Se ha detectado un error visual en la vista principal de la página, concretamente en la columna de Waiting for result, justo cuando acaba la columna hay una línea de texto que no deberia de aparecer.

**Comment by Josdelsan** [comment]
Había un error en algunas variables de la plantilla de la página de inicio que hacía que los mensajes no se mostraran adecuadamente, ya está arreglado en la rama de desarrollo
