### ISSUE TITLE
Cambiar el color de la navbar

### ISSUE THREAD

**Issue by lNoelia** [decide-part-aracena/decide-part-aracena#158]
Hay que cambiar el color de la navbar de negro a azul. Motivo: peticion del profesor

**Comment by rosmolarr** [comment]
```
nav.navbar {
    background-color: #CC1414;
}
```
Prueba con esto en el css que a lo mejor funciona

**Comment by Josdelsan** [comment]
@rosmolarr Muchas gracias, al final he usado `navbar-primart` como clase en boostrap
