### ISSUE TITLE
Preparación de Docker para el despliegue del M3

### ISSUE THREAD

**Issue by lNoelia** [decide-part-aracena/decide-part-aracena#83]
En esta issue se pretende :

- [x] - Crear un superuser Django para hacer posible el uso del despliegue 
- [ ] - Crear un script que popule la base de datos y tener ejemplos para trabajar en nuestras funcionalidades para el M3
- [x] - Optimizar los archivos de docker 
- [x] - Cambiar la forma de hacer el despliegue para poder hacer despliegue de docker en una rama concreta con los archivos locales para dar soporte a los secrets y solucionar los problemas ocurridos en el M2

**Comment by lNoelia** [comment]
He estado probando con varias opciones sobre la creación de un super usuario pero no he conseguido acabarlo. He creado un archivo createsuperuser.py para la inicialización del super usuario al hacer docker compose up ( estos cambios se encuentran en el fork de decide-part-aracena-pruebas). Además, mi maquina virtual parece que va más lenta de lo normal y se apaga automaticamente al usar el comando de docker compose up, asi que de momento no puedo seguir haciendo pruebas. ¿Alguien podría seguir probando ?

**Comment by Josdelsan** [comment]
Se han refactorizado los archivos de docker compose y los dockerfile. Ahora se puede hacer `docker compose up` desde la propia carpeta del proyecto y en vez de bajarse la ultima version de master, creará la imagen decide_web a partir de los archivos locales. Al copiar los archivos locales ahora no hay problema con las funcionalidades que dependen de secretos si se tiene configurado el `archivo secrets_settings.py`.

Se recomienda forzar la creación de las imágenes de nuevo con `docker compose up --build` o borrar las imágenes antes de probar.

Se encuentra un problema ya que la funcionalidad #4 se sirve de la constante BASEURL para construir la url que se manda por correo. El archivo `docker_settings.py` contiene referencia a la ip del contenedor dentro de la red en docker. En producción, para garantizar el correcto funcionamiento, en principio habría que cambiar esta URLBASE cambiando el `docker_settings.py` antes de construir la imagen o modificando el archivo `local_settings.py` una vez corriendo el contenedor usando el comando `docker cp`.

Voy a probar a crear super usuarios a partir del script.

**Comment by Josdelsan** [comment]
Se ha añadido soporte a la creación se super usuarios al hacer `docker compose up`.  Para crear un superusuario en decide al levantar el servicio hay que crear un archivo de nombre `.env` en el mismo directorio de trabajo donde se encuentra el archivo `docker-compose.yml`. El archivo debe contener la siguiente estructura:

```
SUPER_USER_NAME="usuario"
SUPER_USER_EMAIL="correo@valido.es"
SUPER_USER_PASSWORD="contraseña"
```

Modificar los datos del usuario al gusto de cada uno. Si no existe este archivo o las variables está mal el contenedor no se ve afectado, solo afecta a la creación del super usuario.

Se sigue buscando ideas de como gestionar el archivo de secretos `secrets_settings.py`. De momento se propone copiarlo al directorio `decide` antes de ejecutar el `docker compose up` o si partimos de la imagen aislada de `decide_web` ya corriendo, se puede copiar con el comando `docker cp` antes de ejecutar el comando que levanta decide.

**Comment by Josdelsan** [comment]
@lNoelia creo que "Crear un script que popule la base de datos y tener ejemplos para trabajar en nuestras funcionalidades para el M3" se va del scope de esta incidencia y debido al poco tiempo que queda podemos dar por terminada la configuración.

**Comment by lNoelia** [comment]
Tienes razón, creo que se va fuera del alcance de esta incidencia. Cierro la incidencia
