### ISSUE TITLE
Más tipos de tests

### ISSUE THREAD

**Issue by rosmolarr** [decide-part-aracena/decide-part-aracena#93]
Se propone intentar hacer más tipos de tests para ampliar la cobertura de código de la issue #13

**Comment by lNoelia** [comment]
He intentando añadir las claves de github para poder usarlas en los test pero al preguntar por las claves en los test no encuentra las keys que pido. Ahora voy a intentar hacer uso del archivo "secret_settings.py" que se obtiene del .example para obtener esas claves y poder realizar los test en local y que en github simplemente lance una excepción ya que no puede encontrar el archivo.

**Comment by lNoelia** [comment]
Las pruebas de vista sobre la conexión a las apis de google, facebook y discord para el inicio de sesión. El problema es que en los test, el puerto va cambiando y no he sido capaz de encontrar alguna manera de que siempre se elija el mismo puerto al realizar esos test. Este problema, causa que  las APIs, que solo permiten peticiones y redirecciones a uris que se han descrito al crear las aplicaciones. He decidido comentar cómo se harían los test para probar esa funcionalidad "a mano" para que se puedan "probar" pero no voy a realizar los test sobre el inicio de sesión con redes sociales. 

Por otra parte, se han añadido test que prueban el modelo de usuarios (CRUD) y comprobaciones en la interfaz de registro de usuarios, en la que se comprueban que no se pueda crear una cuenta con un email en uso, que tanto la contraseña como la comprobación de la contraseña sean iguales y que las contraseñas tengan la longitud esperada.
